#!/usr/bin/env sh
set -eu

cmd="$HOME/.local/share/tmux-up"

# configs session - config editing windows
$cmd -f --cwd ~/.config/river  configs river     'nvim .'
$cmd -f --cwd ~/.config/waybar configs waybar    'nvim .'
$cmd -f --cwd ~                configs tmux-conf 'nvim ~/.tmux.conf'
$cmd -f --cwd ~                configs nvim-conf 'nvim ~/.config/nvim/init.lua'

# repos session - development windows
$cmd -f repos main
$cmd -f repos nvim 'nvim .'
